# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.IntegerField(choices=[(0, 'admin'), (1, 'alumno'), (2, 'fijo'), (3, 'ambulante')])),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('contraseña', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('formasDePago', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True)),
                ('horarioIni', models.CharField(blank=True, max_length=200, null=True)),
                ('horarioFin', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField(default=-33.457785)),
                ('lng', models.FloatField(default=-70.663808)),
                ('alertaActiva', models.CharField(default='no', max_length=200)),
                ('favoritos', models.ManyToManyField(blank=True, to='main.Cliente')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=200)),
                ('categorias', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Cerdo'), (1, 'Chino'), (2, 'Completos'), (3, 'Egipcio'), (4, 'Empanadas'), (5, 'Ensalada'), (6, 'Japones'), (7, 'Pan'), (8, 'Papas fritas'), (9, 'Pasta'), (10, 'Pescado'), (11, 'Pollo'), (12, 'Postres'), (13, 'Sushi'), (14, 'Vacuno'), (15, 'Vegano'), (16, 'Vegetariano')], max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('precio', models.PositiveSmallIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComida', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField()),
                ('fecha', models.CharField(default='2017-06-27', max_length=200)),
                ('idVendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
            options={
                'db_table': 'transacciones',
            },
        ),
    ]
