# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
