# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170626_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='main.Cliente'),
        ),
    ]
