# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170626_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.CharField(default='2017-06-27', max_length=200),
        ),
    ]
