# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170625_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoritos',
        ),
        migrations.AddField(
            model_name='imagen',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(to='main.Usuario'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario'),
        ),
    ]
